compilation:
  model: .specalign/models/default.yaml
  spec_files:
  - .specalign/specs/factual-accuracy.md
  - .specalign/specs/forbidden-words.md
  - .specalign/specs/html-output.md
  - .specalign/specs/response-structure.md
  - .specalign/specs/response-style.md
  - .specalign/specs/seo-content.md
  timestamp: '2026-01-14T03:44:56.319819+00:00'
